resources/js/components/Publish/PublishForm.vue

Fixes the dirty state warning on create new model.
https://github.com/doublethreedigital/runway/issues/41

Adds nexttick for dirty state avoidance.

---

resources/js/components/Publish/PublishForm.vue

Adds mod+s, mod+return key bindings for saving models.
Adds https://github.com/doublethreedigital/runway/issues/42

Adds support for save key bindings on publish form

---

resources/js/components/Publish/PublishForm.vue

Adds invalid warnings on specific fields rather than single generic toast notification.
Closes #43

Add individual validation errors to single fields

---

resources/js/components/Publish/PublishForm.vue
resources/views/create.blade.php
resources/views/edit.blade.php
routes/cp.php
src/Fieldtypes/BaseFieldtype.php
src/Fieldtypes/BelongsToFieldtype.php
src/Fieldtypes/HasManyFieldtype.php
src/Http/Controllers/ResourceController.php
tests/Http/Controllers/ResourceControllerTest.php

This pull request adds support for creating/editing Runway models via the stack things on the Runway fieldtypes. 
This pull request also fixes an issue where if you create a model with a HasMany fieldtype, the HasMany relations would not be saved.
Video demo: https://www.loom.com/share/c0d9cdaf476f472cbb206418ba52141b
Closes #76

Fieldtype Stacks

---

src/Tags/RunwayTag.php

Add ability to add a relationship to the query. No test at the moment, need to understand your testing framework.
Closes #83

Add `with` parameter

---

src/Console/Commands/GenerateMigration.php

Make migration filename singular

---

src/Fieldtypes/BaseFieldtype.php
src/Fieldtypes/HasManyFieldtype.php

First thank you very much for this wonderful package :)
Currently, only one-to-many relations are supported through the has_many fieldtype.
This PR adds support for many-to-many relations. Actually, it's more a proof-of-concept as there are perhaps more things to change.

Add support for many-to-many relations

---

src/Fieldtypes/HasManyFieldtype.php

Allows you to determine whether the create button appears in HasMany field types.

Feature: Allow toggling of create button in HasMany

---

README.md

Update the link for frontend documentation to link to the correct page.

Update frontend routing documentation link

---

resources/js/components/Publish/PublishForm.vue
resources/views/edit.blade.php
src/Http/Controllers/ResourceController.php

From now on, whenever you create a new related record using the 'Create & Link Item' button on the BelongsTo fieldtype, the relation will automatically be set on that new record.
Closes #112.
https://www.loom.com/share/757e6330b1274ff8a492169048dbcd0e

Automatically set relation when creating with BelongsTo fieldtype

---

src/Resource.php

Exclude imported fieldsets when generating listable columns

---

.github/workflows/tests.yml
composer.json
composer.lock

This pull request adds PHP 8.2 to the testing workflow. It also removes the versions of Orchestra from the composer.json file we're no longer using.

PHP 8.2 Support

---

resources/js/components/Publish/PublishForm.vue
resources/views/create.blade.php
resources/views/edit.blade.php

This pull request adds a tiny feature to Runway: options on the save button. It's been a feature on entries for a while and I'm honestly surprised no one has requested it this far.

Save Button Options

---

resources/js/components/Listing/ListingView.vue

Show 'Edit' link when front-end routing is disabled

---

src/Http/Controllers/ResourceActionController.php

Tiny fix on getSelectedItems function to return the correct items, rather than first in DB  🙌

Fix: Action Controller returning incorrect items to actions

---

src/Tags/RunwayTag.php

This pull request improves how the Runway tag handles pagination to make it more like what Statamic does for collections.
These changes mean that `{{ links:segments }}` will now work when paginating through models, as requested in #212.

Improve pagination in Runway tag

---

src/Http/Controllers/ResourceController.php
tests/Http/Controllers/ResourceControllerTest.php
tests/TestCase.php

Ignore computed fields when saving

---

resources/js/components/Listing/ListingView.vue

This pull request fixes some slightly broken parts of the listing table after some changes in statamic/cms#8001 (which happened after my previous compatibility changes).
Statamic 4 for the win 🔥

Fix slightly broken listing table in v4

---

src/Fieldtypes/BaseFieldtype.php
tests/Fieldtypes/BelongsToFieldtypeTest.php
tests/Fieldtypes/HasManyFieldtypeTest.php

This pull request adds pagination to the fieldtype's selections listing.

Add pagination to fieldtype items

---

src/Http/Controllers/ResourceController.php

This pull request fixes an issue where a relationship field (Has Many / Belongs To / Users / Entries / etc), when situated first in the list of columns, would output JSON & become the title field (the one you can click on to go into the resource).
This PR addresses it by filtering out fields with the `relationship` index component from being the primary/title field in the listing table.
Fixes #277.

Fix issue with relationship field being picked up as title field

---

src/Fieldtypes/BelongsToFieldtype.php
src/Fieldtypes/HasManyFieldtype.php
src/GraphQL/ResourceIndexQuery.php
src/GraphQL/ResourceShowQuery.php
src/GraphQL/ResourceType.php
src/Http/Controllers/ResourceController.php
src/ServiceProvider.php

This pull request contains a suggested fix included in #279 to resolve some issues with the naming of GraphQL stuff.
Fixes #279

Fixes "GraphQL Codegen Type Name Issue"

---

docs/templating.md

Updated the pagination template code to reflect current pagination items.

Update Pagination Code templating.md

---

resources/js/components/Publish/PublishForm.vue

Remove extra border on publish form

---

docs/resources.md
src/Console/Commands/GenerateMigration.php
src/Data/AugmentedModel.php
src/GraphQL/ResourceType.php
src/Http/Controllers/ResourceController.php
src/Http/Resources/ResourceCollection.php
tests/Console/Commands/GenerateMigrationTest.php
tests/Http/Controllers/ResourceControllerTest.php
tests/Http/Controllers/ResourceListingControllerTest.php
tests/Routing/FrontendRoutingTest.php
tests/TestCase.php
tests/__fixtures__/database/migrations/2020_12_12_220453_create_posts_table.php
tests/__fixtures__/resources/views/default.antlers.html

This pull request replaces #302 (due to GitHub branch permissions). 
Thanks @morphsteve!

Nesting blueprint fields in JSON columns

---

src/Console/Commands/GenerateMigration.php
tests/Console/Commands/GenerateMigrationTest.php

This pull request completes all of the previously incomplete tests for the generate migrations command. This should hopefully help to ensure all is working as it should be.

[5.x] Complete tests for generate migrations command

---

resources/js/components/Fieldtypes/HasManyRelatedItem.vue
resources/js/components/Fieldtypes/Relationship/RelationshipFieldtype.vue
src/Fieldtypes/BaseFieldtype.php
src/Fieldtypes/HasManyFieldtype.php

This pull request drops the "Table" mode that was previously available in the Has Many fieldtype. This mode is being removed to help reduce complexity of Runway's fieldtypes.

[6.x] Remove Table Mode

---

resources/js/components/Publish/PublishForm.vue
resources/views/create.blade.php
resources/views/edit.blade.php
resources/views/index.blade.php
src/Http/Controllers/CP/ResourceController.php

This pull request makes some tweaks to publish form actions. This includes introducing a new dropdown with an "Edit Blueprint" link on the index & edit resource pages.

[6.x] Improve publish form actions

---

src/Http/Controllers/CP/ResourceController.php

[6.x] Include Model ID in Publish Form values

---

docs/upgrade-guides/v5-x-to-v6-0.md

Noticed this small mistake in the docs while upgrading 🙂.

Fix add/remove markup in upgrade guide

---

.editorconfig
composer.json

Make it easier for those of us who dont want to use VSCode.

[6.x] Add .editorconfig and pint

---

src/Data/AugmentedModel.php
tests/Data/AugmentedModelTest.php
tests/__fixtures__/app/Models/Post.php

This PR adds any 'appends' to the default model augmentation keys.

[6.x] Add model appends to augmentation

---

src/Fieldtypes/BaseFieldtype.php

Adds check for instance of BelongsToMany for augment and shallowAugment.

[6.x] Fixed augmentation for BelongsToMany relationships

---

docs/frontend-routing.md
src/Console/Commands/RebuildUriCache.php

- Adds ability to scope resources for uri generation when running command `php please runway:rebuild-uris`
- Adds documentation for defining the scope in your model.

[6.x] Scope for generating runway route uri

---

tests/Console/Commands/GenerateBlueprintTest.php
tests/TestCase.php

This pull request aims to fix an issue where a good chunk of the test suite is suddenly failing. It wasn't failing when I tagged the last release but it is now. 🤷‍♂️

[6.x] Fix failing tests

---

.gitignore
composer.json
phpunit.xml

This pull request updates to PHPUnit 10, since it's required for the Laravel 11 upgrade.

[6.x] PHPUnit 10

---

docs/search.md

And added example that better relates to the rest of the page

[6.x] Fix incorrect collection handle plural

---

src/Http/Controllers/CP/Traits/PreparesModels.php
tests/Console/Commands/GenerateBlueprintTest.php
tests/Console/Commands/RebuildUriCacheTest.php
tests/GraphQL/ResourceInterfaceTest.php
tests/Http/Controllers/CP/ResourceControllerTest.php
tests/RunwayTest.php
tests/__fixtures__/app/Models/User.php
tests/__fixtures__/config/runway.php
tests/__fixtures__/database/migrations/2014_10_12_000000_create_users_tables.php
tests/__fixtures__/resources/blueprints/vendor/runway/user.yaml

This pull request adds some special handling around the Role & Group fields when the `User` model is configured as a Runway resource. 
Closes #485.

[7.x] Handle roles and users fields for user models

---

resources/js/components/Publish/PublishForm.vue
src/Actions/Publish.php
src/Actions/Unpublish.php
src/Http/Controllers/CP/Traits/ExtractsFromModelFields.php
src/Http/Resources/CP/ListedModel.php
src/Traits/HasRunwayResource.php

This pull request makes a couple of small improvements to the publish state code, added in #506. 
Nothing major, just making the code slightly more readable 😄

[7.x] Refactor some publish state code

---

composer.json
tests/Http/Controllers/CP/ModelRevisionsControllerTest.php
tests/Http/Controllers/CP/PublishedModelsControllerTest.php
tests/Http/Controllers/CP/RestoreModelRevisionController.php

This pull request fixes some namespacing issues in the test suite.
Fixes #538.

[7.x] Fix namespacing issues in test suite

---

src/Actions/Publish.php
src/Actions/Unpublish.php
tests/Actions/PublishTest.php
tests/Actions/UnpublishTest.php
tests/TestCase.php

[7.x] Don't show actions when not models

---

resources/js/components/Publish/PublishForm.vue

[7.x] When revisions are enabled, set the save button to Save Changes

---

src/Traits/HasRunwayResource.php

[7.x] Handle json data in revisions

---

docs/blueprints.md

[7.x] Update blueprints.md

---

src/Data/HasAugmentedInstance.php

Fixes https://github.com/statamic-rad-pack/runway/issues/566

[7.x] Updated the `HasAugmentedInstance` trait so that it is compatible with Statamic

---

src/Console/Commands/GenerateMigration.php
src/Http/Controllers/CP/ResourceController.php
src/Routing/ResourceResponse.php
src/Runway.php
tests/Actions/DeleteModelTest.php
tests/Actions/DuplicateModelTest.php
tests/Actions/PublishTest.php
tests/Actions/UnpublishTest.php
tests/Fieldtypes/BelongsToFieldtypeTest.php
tests/Fieldtypes/HasManyFieldtypeTest.php
tests/RelationshipsTest.php
tests/Routing/RoutingModelTest.php

This pull request runs Laravel Pint as some of the default rules changed in a recent Pint release.

[7.x] Run Laravel Pint

---

src/Http/Controllers/ApiController.php

This pull request fixes an issue where an exception would be thrown when trying to use the REST API on a resource with a plural handle, like `orders`.
`Runway could not find [order]. Please ensure its configured properly and you're using the correct handle.`
```php
\DuncanMcClean\SimpleCommerce\Orders\OrderModel::class => [
'name' => 'Orders',
'handle' => 'orders',
'blueprint' => 'order',
'hidden' => true,
'read_only' => true,
],
```
```php
'resources' => [
// ...
'runway' => [
'orders' => true,
],
],
```

[7.x] Fix issue when using plurals as resource handles

---

resources/js/components/data-list/Filters.vue

This pull request fixes an error you'd get when trying to remove a filter on the listing table.
Fixes #607.

[7.x] Fix error when removing filters

---

src/Actions/DeleteModel.php
src/Actions/Publish.php
src/Actions/Unpublish.php
src/Traits/HasRunwayResource.php

This pull request improves the feedback when actions fail, mirroring the changes from statamic/cms#10264.

[7.x] Improve feedback when action fails

---

src/Policies/ResourcePolicy.php

This pull request fixes an issue with publish permissions for non super users.
Fixes #620.

[7.x] Fix publish permission for non super users

---

composer.json
src/Fieldtypes/BaseFieldtype.php
src/Scopes/Fields.php
src/Scopes/Fields/Models.php
src/Scopes/Status.php
src/ServiceProvider.php
tests/Query/Scopes/Filters/ModelsTest.php

This pull request tidys up Runway's `ServiceProvider` after the recent introduction of addon autoloading.

[7.x] Clean up `ServiceProvider`

---

docs/blueprints.md

Hi,
Thanks for a great addon!
Feels like this is supposed to refer to the 'Max items' setting.

[7.x] Update settings title

---

resources/js/components/data-list/Filters.vue
resources/js/components/resources/Listing.vue
src/Scopes/Fields.php

This pull request fixes an couple of issues regarding filters on the Runway listing table.
Closes #613.

[7.x] Fix listing filters

---

src/Traits/HasRunwayResource.php

This pull request fixes an error when searching the Control Panel listing when nested fields are showing.

[8.x] Fix search on listing table with nested fields

---

src/Fieldtypes/BaseFieldtype.php

Fix error when searching via fieldtype

---

package-lock.json
package.json
resources/js/components/inputs/relationship/Item.vue
resources/js/components/resources/Listing.vue
resources/js/components/resources/PublishForm.vue
resources/js/components/resources/View.vue
resources/js/components/resources/Widget.vue
resources/js/components/revision-history/History.vue
resources/js/components/revision-history/Revision.vue
vite.config.js

This pull request changes how we import code from Statamic.

[9.x] JS Imports

---

composer.json
docs/frontend-routing.md
resources/js/components/resources/PublishForm.vue
resources/views/edit.blade.php
routes/cp.php
src/Data/AugmentedModel.php
src/Http/Controllers/CP/ModelPreviewController.php
src/Http/Controllers/CP/ResourceController.php
src/ModelRepository.php
src/Resource.php
src/Routing/ResourceRoutingRepository.php
src/Routing/Traits/RunwayRoutes.php
src/Search/Searchable.php
src/ServiceProvider.php
src/Traits/HasRunwayResource.php
tests/Data/AugmentedModelTest.php
tests/Http/Controllers/CP/ModelPreviewControllerTest.php
tests/ModelRepositoryTest.php

This pull request adds the ability to live preview models, like you can with entries. 
Closes #446.

[9.x] Live Preview

---

src/Http/Controllers/CP/Traits/PreparesModels.php

Avoid saving revealer fields
