.gitattributes, README.md
adding all files to .gitattributes, which the composer package don't need.
Should always include:
- Pipline/Github Actions
- Tests Files
- Docs
- etc.
=> add gitattributes to reduce composer package size 

src/Support/ModelFinder.php
On a Model with a custom $primaryKey set, I get the following error on its index page:
`Illuminate\Routing\Exceptions\UrlGenerationException
Missing required parameter for [Route: statamic.cp.runway.edit] [URI: cp/runway/{model}/{record}] [Missing parameter: record]. (View: vendor/doublethreedigital/runway/resources/views/index.blade.php)
`
Changing to [getRouteKeyName()](https://laravel.com/api/8.x/Illuminate/Database/Eloquent/Model.html#method_getRouteKeyName) instead of `getRouteKey()` fixes the error for me.
=> Fix for custom $primaryKey

resources/js/components/Publish/PublishForm.vue, resources/js/cp.js, resources/views/create.blade.php, resources/views/edit.blade.php, src/Http/Controllers/ResourceController.php, src/Routing/ResourceRoutingRepository.php, src/Routing/Traits/RunwayRoutes.php, src/ServiceProvider.php
This pull request switches the publish form used by Runway from being the default `publish-form` component to being a custom publish form component.
*Why?*, you might ask? Well, because in #28 we're introducing front-end routing and as part of that card I want to add a 'Visit URL' button to the publish form and this is the only way to do that. 
This PR builds on the frontend setup that I did on another branch. 
Need to be merged before #28
=> Custom Publish Forms

src/Fieldtypes/BaseFieldtype.php, src/Resource.php
1. Fixes resource index when the resource model has a custom `$primaryKey` (or `getRouteKeyName()`).
2. Fixes BelongsTo fieldtype item data when the resource model uses a custom $primaryKey.
=> Custom $primaryKey fixes

resources/js/components/Listing/ListingView.vue
Listing config should be an object, since it's used as one.
=> Fix prop issue in ListingVue

resources/js/components/Listing/ListingView.vue, resources/views/index.blade.php
Columns is a data name already use by the parent `Listing` vue component.
Let's rename the prop to `initialColumns` to avoid conflicts
=> Fix conflicting props / data name for columns

src/AugmentedRecord.php, src/Http/Controllers/ResourceController.php, tests/Http/Controllers/ResourceControllerTest.php
When editing a Date field, let's use the user defined format if set, or a sensible default if not
=> Use date field's own format to edit the resource

src/Http/Controllers/ResourceController.php
If in a model there is a casted property like array, collection, object, we don't need to json encode it, otherwise the caster will "double encode it"
=> don't json encode casted properties

src/Fieldtypes/BaseFieldtype.php, tests/Fieldtypes/BelongsToFieldtypeTest.php
This pull request makes some improvements to the built-in 'Belongs To' fieldtype - well, mainly just a whole bunch of bug fixes 🐛 .
I've recorded a brief Loom demonstrating the fixes - the only bit I still need to do is fix the state just after selection.
https://www.loom.com/share/4392b64201ef411db5ceaa416f1200a1
Fixes #67
=> Fieldtype Improvements

src/Fieldtypes/BaseFieldtype.php
When a relationship field contains a record which has been deleted, the entry publish form errors with `Call to a member function getKey() on null` at line 160.
This adds a null check on $record and returns the title as '[id] (not found)'.
n/a
=> Null check on $record in toItemArray()

docs/resources.md, src/Console/Commands/GenerateBlueprint.php, src/ServiceProvider.php
This pull request introduces a feature where Runway can generate blueprints for you, based on your model's database schema.
> I've straight copy/pasted this from the documentation, for an up-to-date version, please [review the latest Runway docs](https://runway.duncanmcclean.com/resources).
Before you can generate, you'll need to install the [`doctrine/dbal`](https://github.com/doctrine/dbal) package as it'll be used by Runway to analyse your database columns. You'll also need to have migrated your database already.
As well as having your model setup, you will also need to add the resource(s) to your `config/runway.php` config.
To generate a blueprint for a specific resource:
```
php please runway:generate-blueprints resource-handle
```
You may also run this same command for all …
=> Generate blueprints from database

docs/templating.md, src/Tags/RunwayTag.php, tests/Tags/RunwayTagTest.php, tests/TestCase.php
This pull request implements the ability to specify a [local Eloquent scope](https://laravel.com/docs/8.x/eloquent#local-scopes) with the Antlers tag provided by Runway.
```php
// app/Models/Post.php
public function scopeFood($query, $first, $second)
{
// $first, $second
$query->whereIn('title', ['Pasta', 'Apple', 'Burger']);
}
public function scopeHealthy($query)
{
$query->whereIn('title', ['Apple']);
}
```
```antlers
{{ runway:post scope="food:arg1,arg2|healthy" }}
<h2>{{ title }}</h2>
<p>{{ intro_text }}</p>
{{ /runway:post }}
```
Closes #82
=> Eloquent scopes with Runway tag

src/Http/Controllers/ResourceListingController.php, tests/Http/Controllers/ResourceListingControllerTest.php
If a resource has a HasMany fieldtype on it and you try to search for one of it's records, you would previously get an error. This pull request fixes the issue so HasMany fields are not searched upon (since it does some magic under the hood and isn't an actual database column).
This didn't seem to be an issue for SQLite which seemed to silence the exception.
Replaces #99
=> Fix search on resources with HasMany field

src/Http/Requests/DestroyRequest.php, src/Http/Requests/StoreRequest.php
The permissions for `store` and `destroy` are singular but the checks in the requests were plural, which caused an `Authorization failed` error.
=> proper permission checks

docs/fieldtypes.md, src/Fieldtypes/HasManyFieldtype.php, tests/Fieldtypes/HasManyFieldtypeTest.php
Basically we by-pass all the logic you wrote and only run it if resourceHandle is available in the route, which it isnt on Stache entries.
This then allows the normal relationship field logic to run and the items get inserted as ids in the yaml array.
None
=> Feature: Allow HasMany to work on Stache entries

docs/templating.md, src/GraphQL/ResourceIndexQuery.php, src/Http/Controllers/ResourceListingController.php, src/Http/Resources/ResourceCollection.php
This pull request introduces eager loading behind the scenes for 'index queries' made by Runway. This will almost certainly fix #113.
Big thanks to @DanielDarrenJones for pairing with me on this one!
Runway will now automatically ['eager load'](https://laravel.com/docs/8.x/eloquent-relationships#eager-loading) relations for any Runway fieldtypes (Belongs To & Has Many), along with the 'runwayUri` relation if front-end routing has been enabled.
This PR doesn't touch the Runway tag as it already allows for developers to specify which models they'd like to eager load in the query.
```antlers
{{ runway:product with="tags|brand|runwayUri" }}
<h2><a href="{{ url }}">{{ name }}</a></h2>
{{ /runway:product }}
```
When we tested the impact of adding the eager loading parameter to the tag, we saw …
=> Performance Tweaks

.styleci.yml, src/GraphQL/ResourceIndexQuery.php, src/Http/Controllers/ResourceListingController.php
This pull request fixes two issues brought about by the introduction of eager loading (#114) the other day:
If the handle of your BelongsTo/HasMany _(mostly for HasMany's though, since we strip `_id` from the end of field handles)_ field was different from that of your relation name, you would run into an issue where Runway would try to eager load a relationship that didn't exist.
* Relation name: `supportConversations`
* Field handle: `support_conversations`
```
[2022-02-08 10:39:16] local.ERROR: Call to undefined relationship [support_conversations] on model [App\Models\Customer]. {"userId":"cba0aed3-26f9-4ca9-a67f-8261a605d37b","exception":"[object] (Illuminate\\Database\\Eloquent\\RelationNotFoundException(code: 0): Call to undefined relationship [support_conversations] on model …
```
=> Fix issue with Eager Loading

src/Http/Resources/ResourceCollection.php
This pull request will fix an issue where multi-word relationships wouldn't be getting eager loaded properly. We weren't `Str::camel` casing the multiple words.
Before this fix, you'd end up with the eager loading itself actually working BUT you'd also see a whole load of extra (n+1) queries happening, as if we weren't even using eager loading.
=> Eager Loading: Improve 'magic relation guessing'

src/GraphQL/ResourceIndexQuery.php, src/Http/Controllers/ResourceListingController.php, src/Http/Resources/ResourceCollection.php, src/Resource.php, tests/ResourceTest.php
This pull request refactors the way Runway gets the relation names which should be eager loaded in the CP & via GraphQL. This PR also includes some tests for the magic logic that we provide.
=> Refactor eager loading magic ✨ 

src/Fieldtypes/BaseFieldtype.php
This is a performance related PR. We are using runway on a site that often outputs the same items on a page. Instead of getting them each time, lets `Blink` them so we only do one database query per model on the front end.
=> Store models in blink to prevent multiple DB calls

docs/resources.md, resources/js/components/Publish/PublishForm.vue, resources/views/edit.blade.php, resources/views/index.blade.php, src/Actions/DeleteModel.php, src/Http/Requests/CreateRequest.php, src/Http/Requests/StoreRequest.php, src/Http/Requests/UpdateRequest.php, src/Resource.php, src/Runway.php, tests/Http/Controllers/ResourceControllerTest.php
This pull request introduces the ability to mark resources as 'read only'. With a read-only resource, users won't be able to create new records & won't be able to make changes when editing existing records.
=> 'Read Only' Resources

docs/resources.md, src/Resource.php, src/Runway.php, src/ServiceProvider.php
This pull request allows for better customisation around the Control Panel Nav Items that Runway registers for your resources (unless told otherwise).
You can now set a custom title and push the nav item into a section of your choice.
Related to #119
=> Customisations around CP Nav Items

docs/fieldtypes.md, src/Fieldtypes/BaseFieldtype.php
This pull request implements a new `with` config option for Runway fieldtypes so you can specify any relationships you wish to be eager loaded when the Runway field is augmented.
I've just ran into a case where I've needed this as otherwise, some of the information needed wouldn't be pulled in.
=> Ability to specify relationships to eager load when using Runway fieldtypes

src/Fieldtypes/BaseFieldtype.php
This pull request fixes an issue in the eager loading feature introduced in #145. Essentially, when a relationship is looked up, it's returned and we then cache it in the Blink cache.
However, if we go and do a lookup for the same model later on, with eager loaded relations set on the field, it would use the cached version of the model from earlier, without any of the relations eager loaded in.
This PR fixes that by using a unique key depending on the eager loaded relationships set on the field's config.
=> Store eager loaded relations in Blink cache key

src/Http/Controllers/ResourceController.php
This pull request adds the `json` column cast to our list of cast types where we won't encode arrays as JSON.
Fixes doublethreedigital/simple-commerce#649
=> Don't "double encode" field with JSON column cast

src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/ResourceListingController.php
This pull request fixes search in Runway's fieldtypes, when a `runwaySearch` scope is present on the resource's model. The behaviour is now the same as it is on the index listing table.
Now, if a `runwaySearch` scope exists, it'll be used, otherwise, it'll fallback to Runway's default search logic.
Fixes #149
=> Correct behaviour of `runwaySearch` scope when searching in fieldtype

src/Fieldtypes/BaseFieldtype.php, tests/Fieldtypes/BelongsToFieldtypeTest.php, tests/Fieldtypes/HasManyFieldtypeTest.php
Right now after you select an item, the title of it changes back to the previous behaviour (first listable column).
=> Use the formatted title on the item

src/Fieldtypes/BaseFieldtype.php
This pull request fixes #156 by preventing an error from happening when attempting to augment a model that doesn't exist (eg. when the model has been deleted but the reference is still there).
=> Prevent error when attempting to augment model that doesn't exist

src/Resource.php, src/Routing/RoutingModel.php
This pull request fixes #157, where you'd get an error about 'supplements' if you were to try and use the `{{ nav:breadcrumbs }}` tag on Runway's front-end routes.
=> Fix issues when using {{ nav:breadcrumbs }} tag on front-end routes

docs/resources.md, src/Http/Controllers/ResourceListingController.php, src/Resource.php, src/Runway.php, tests/Http/Controllers/ResourceListingControllerTest.php
This pull request implements two new configuration options to Runway, allowing developers to specify the order in which they want models to be returned.
Previously, you would have to do something like this:
```php
public function scopeRunwayListing(Builder $query)
{
return $query->reorder('price', 'asc');
}
```
Whereas now you can use these configuration options:
```php
'resources' => [
\App\Models\Order::class => [
'name' => 'Orders',
// In this case, orders will the highest total will be displayed first.
'order_by' => 'total',
'order_by_direction' => 'DESC',
],
],
```
Closes #160
=> Add config options to order models in Listing Tables

resources/js/cp.js, src/Fieldtypes/BaseFieldtype.php
This pull request fixes an issue where index fieldtypes wouldn't be used when displaying fields in a relationship stack.
For example, in the screenshot below, the product data would be shown as JSON text but now it correctly links to the products (as it does from the standard listing table).
=> Use index fieldtypes in Runway stacks

docs/frontend-routing.md, src/Routing/Traits/RunwayRoutes.php
This pull request allows for invalidating parts of the static cache when models are updated.
In your `static_caching.php` config file, do something like this to invalidate specific URLs:
```php
'invalidation' => [
'class' => null,
'rules' => [
'runway' => [
'product' => [
'urls' => [
'/products/*',
],
],
],
],
],
```
Closes #166
=> Invalidate static cache when models are updated

resources/js/components/Publish/PublishForm.vue
This pull request fixes #172 by adding a Save button at the bottom of the publish form for smaller screens.
=> Show Save button on smaller screens

resources/js/components/Publish/PublishForm.vue, resources/views/create.blade.php, resources/views/edit.blade.php, resources/views/index.blade.php, src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/ResourceController.php
This pull request wraps (hopefully all) of the strings you can see from Runway in the Control Panel, in Laravel's localisation helper to allow for users to translate them.
Related: #176 #177
=> Wrap strings in Laravel's localisation helper

src/Actions/DeleteModel.php
This will pick out the first item from the items collection and use the single item visibility function to see if the delete button should be visible.  There might be more elegant ways to this but it seems to do the job and should also be able to handle null and non Model objects.
=> Hide bulk delete button for read only resources

.github/workflows/tests.yml, composer.json, composer.lock, rector.php, src/AugmentedRecord.php, src/Console/Commands/GenerateBlueprint.php, src/Console/Commands/GenerateMigration.php, src/Console/Commands/ListResources.php, src/Exceptions/ResourceNotFound.php, src/Fieldtypes/BaseFieldtype.php, src/Fieldtypes/HasManyFieldtype.php, src/GraphQL/ResourceIndexQuery.php, src/GraphQL/ResourceShowQuery.php, src/GraphQL/ResourceType.php, src/Http/Controllers/ResourceActionController.php, src/Http/Controllers/ResourceController.php, src/Http/Controllers/ResourceListingController.php, src/Http/Resources/ResourceCollection.php, src/Resource.php, src/Routing/ResourceResponse.php, src/Routing/RoutingModel.php, src/Runway.php, src/ServiceProvider.php, src/Tags/RunwayTag.php
This pull request introduces some breaking changes around what versions of PHP/Laravel/Statamic are supported by Runway.
The list is now:
* PHP 8.1
* Laravel 9
* Statamic 3.4
All three of these dependencies have new versions coming within the next few months so I thought it would be a good time to drop support for old versions, in preparation for what's coming.
This PR includes some automatic code changes by [Rector](https://github.com/rectorphp/rector) which attempts to refactor your code to use the latest & greatest in PHP.
=> PHP 8.1 / Laravel 9 / Statamic 3.3 minimum compatibility

src/Fieldtypes/BaseFieldtype.php
This pull request resolves #185 (an issue when using the Has Many fieldtype in 'Table' mode). 
Previously, if you had a column like `brand_id`, it would show something like 'Brand Id' as the column name (which it shouldn't really be doing).
Instead, this pull request makes it so the field's "Display" text is used (which might be `Brand - more user friendly).
Below is a screenshot on my sandbox site now it's resolved:
=> Runway Fieldtypes: Columns should use a field's 'Display' text, instead of the handle

src/Http/Controllers/ResourceController.php, tests/Http/Controllers/ResourceControllerTest.php
This pull request resolves an issue where saving a record via a publish form inside a stack would fail when the resource inside the stack includes a BelongsTo field.
* So say, you had a 'Locations' resource. 
* When editing locations, you can create/edit 'Location Updates'
* The Location Updates resource contains a Belongs To field to any resource
* When saving the Location Update in the stack,  the user would receive an error
Essentially, whenever you save an entry from inside a stack, it's trying to send back the model data & data about the model's relations.
The reason we're returning information about the model's relations is because they might be needed if the Runway fieldtype is in "Table" mode (depending on the listable columns there).
Runway tries to loop through the fields in …
=> Fix error with BelongsTo fieldtype when saving via a publish form inside a stack

src/Http/Controllers/ResourceController.php
This pull request fixes an issue where Runway would encode an array as JSON, even when a valid cast is setup on the Eloquent model.
For context, this is the model:
```php
protected $casts = [
'is_paid' => 'boolean',
'is_shipped' => 'boolean',
'is_refunded' => 'boolean',
'items' => 'json',  // This one!
'grand_total' => 'integer',
'items_total' => 'integer',
'tax_total' => 'integer',
'shipping_total' => 'integer',
'coupon_total' => 'integer',
'use_shipping_address_for_billing' => 'boolean',
'gateway' => 'json',
'data' => 'json',
'paid_date' => 'datetime',
];
```
And this was the blueprint issue it was having issues with...
```yaml
- handle: items
field:
fields:
- handle: id
field:
type: hidden
listable: hidden
display: ID
- handle: product
field:
max_items: 1
mode: default
collections:
- …
```
=> Fix data being encoded by Runway even when a cast is setup

docs/resources.md, src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/ResourceController.php, src/Http/Controllers/Traits/HasListingColumns.php, src/Resource.php, src/Runway.php
This pull request builds on top of the new `title_field` configuration option added in #200.
Essentially, whenever Runway returns a model in the Control Panel (for example: in a fieldtype or in search), it displays a "title".
Up until now, this title was always the first listable field from the resource's blueprint.
However, this PR refactors all usage of `listableColumns()[0]` to pull the "title" from this new configuration option. If no title field is specified, the first listable field will remain the title that gets used.
=> Add `title_field` config option to determine "title" field

docs/resources.md, src/Resource.php, src/Runway.php, src/ServiceProvider.php
This pull request drops the configuration options for Control Panel navigation. 
The section & title of items in the Control Panel Nav can now be easily edited by the new 'CP Nav' preferences section added in statamic/cms#6678.
I've left the icon config option however, as that's not configurable within the new Nav Preferences. However, I've renamed it so you will need to adjust your config:
```php
'resources' => [
\App\Models\Order::class => [
'name' => 'Orders',
'nav' => [
'icon' => 'date',
],
],
],
```
```php
'resources' => [
\App\Models\Order::class => [
'name' => 'Orders',
'cp_icon' => 'date',
],
],
```
=> Drop Nav configuration

src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/ResourceController.php
This pull request fixes an issue where the stacks for relationship fieldtypes were empty upon opening up. There were also a few errors in the console.
This issue was caused by #198 where we added a new required prop (`resource`). This prop was being passed to the 'base' publish forms but not to the publish form when it opened in a stack inside a relationship fieldtype.
This PR fixes that.
Fixes #207
=> 2.x: Fix relationship stacks opening empty

src/Tags/RunwayTag.php
This pull request fixes two issues I spotted earlier today in the Runway tag:
1. If the value passed to the `sort` parameter is `null` (for example: if it's based on a query parameter but it's not present), then previously you'd receive an error. Now any sorting will just be ignored when that's the case.
2. You couldn't *just* provide the column you wanted to sort with, you also had to specify the sort direction you wanted too. Now, you don't have to. If no direction is provided, results will be sorted in `asc` order.
Closes #213
=> Fix `sort` parameter in Runway tag

CHANGELOG.md, docs/control-panel.md, package.json, resources/views/index.blade.php, src/Actions/DeleteModel.php, src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/ResourceListingController.php, src/Http/Requests/CreateRequest.php, src/Http/Requests/EditRequest.php, src/Http/Requests/IndexRequest.php, src/Http/Requests/StoreRequest.php, src/Http/Requests/UpdateRequest.php, src/Http/Resources/ResourceCollection.php, src/ServiceProvider.php, src/UpdateScripts/ChangePermissionNames.php, tests/Helpers/RunsUpdateScripts.php, tests/UpdateScripts/ChangePermissionNamesTest.php, tests/__fixtures__/resources/users/roles.yaml
This PR tackles what was discussed [here](https://github.com/duncanmcclean/runway/discussions/211#discussion-4810850) 
- Add ability to override default permission keys
- Add ability to customize permission labels
- Add detailed docs on how to override permission keys, localize labels and add custom permissions
- Add a "build" script to package.json to allow building on newer Node.js versions
=> feat: Make permission keys configurable

resources/js/components/Listing/ListingView.vue
When clicking the edit link inside a row in a resource listing, before the editing page is loaded, the row gets briefly selected as if the user has clicked the row, not the link.
This will stop the click propagation from the link and prevent the selection from happening.
Originally #219 but I've cherry-picked the commit to avoid pulling over unrelated changes.
=> Prevent resource row selection

src/Http/Controllers/ResourceListingController.php
Stumbled across this today: when trying to search in a simple commerce resource (orders) I kept hitting SQL errors because section fields as well as computed fields were included and the app couldn't find columns for those in the database.
=> Exclude sections and computed values from search

src/Tags/RunwayTag.php, tests/Tags/RunwayTagTest.php
This pull request adds the ability for you to query Eloquent relationships using the `where` parameter on the Runway tag.
```antlers
{{ runway:course as="courses" where="topics:{ get:topics }" }}
{{ /runway:course }}
```
In this case, `get:topics` is the ID of a topic model.
=> Support relationships in `where` parameter on Runway tag

.github/workflows/release.yml, .gitignore, composer.json, package.json, resources/js/components/Fieldtypes/Relationship/RelationshipFieldtype.vue, resources/js/components/Publish/PublishForm.vue, resources/js/cp.js, src/ServiceProvider.php, tests/TestCase.php, vite.config.js, webpack.mix.js
This pull request switches the front-end build tool from Laravel Mix to Vite for speedy build times. ✨
It also means that whenever you're working with Runway locally, you'll no longer need to symlink the `resources/dist` folder when running `npm run dev`.
This was made possible by https://github.com/statamic/cms/pull/6869.
=> Switch to Vite

src/Fieldtypes/BaseFieldtype.php
This pull request fixes an issue I just spotted where sometimes the `$item` here was a `Collection`.
And if it was a `Collection`, then Runway would try and pass the entire collection to the database, instead of the model ID. This was causing a database error.
=> Fix "Column index out of range" error

resources/js/components/Fieldtypes/Relationship/RelationshipTableMode.vue, src/Fieldtypes/BaseFieldtype.php, src/Resource.php
This pull request fixes various issues I've found when using the Runway's Has Many fieldtype in Table mode:
* Columns set to not be listable (with `listable: false`) were still being shown on the table
* Columns weren't using their relevant 'index components' in the table mode (causing data to display differently when compared to listing tables)
* Data wasn't being run through the `preProcessIndex` on their fieldtypes which they should be before being sent to their 'index components'
I also tried to fix an issue I found around the width of the table going outside the fieldtype container but my CSS skills aren't great - when I tried I broke the drop shadows and the actions dropdown. I'll leave that for another time (or for someone else 😆 )
Closes #243
=> Various fixes to Has Many Table Mode

src/Http/Controllers/ResourceController.php, tests/Http/Controllers/ResourceControllerTest.php, tests/TestCase.php
This pull request fixes #240, where you'd get an error when trying to save a model when the field exists in the model's `$appends` array but not in the database.
This PR fixes that by checking for the presence for the field in `$appends` and also checks to make sure there's no 'set mutator' created for it.
=> Don't attempt to set data if it's included in the model's `$appends` array

src/Http/Controllers/ResourceController.php
This pull request fixes #236 - an issue where Runway was querying the `id` column on a related table. However, as no table was specified, the database would throw an error about the query being ambiguous about the table.
This PR fixes that by manually specifying the table for the `id` where statement. It also changes `id` to use the model's primary key (as this may not always be called `id`).
=> Fix ambiguous table error

src/Fieldtypes/BaseFieldtype.php
This pull request makes a tiny fix to ensure breadcrumbs show when opening the inline publish forms provided by Runway's relationship fieldtypes.
=> Ensure breadcrumbs are passed into inline publish form

resources/js/components/Listing/ListingView.vue, resources/views/index.blade.php, src/Http/Controllers/ResourceController.php, src/Http/Controllers/Traits/HasListingColumns.php
This pull request fixes #238.
When the `ListingView` component is initially loaded, it's provided with an `initialColumns` prop which is provided by the `ResourceController`. It then does a request to the server for models.
On this first request, if the columns differ (what was provided in the prop to what was returned in that second request), Statamic will do another request.
This is what was causing two requests to be done when loading the listing table.
As part of this fix, I've also had to re-work how the 'primary column' on the listing table is passed into the view. It's now a prop passed in from the view/controller, instead of being decided inside the `ListingView`'s data.
=> Fix double requests, caused by columns changing

src/Console/Commands/GenerateBlueprint.php
Thanks for this really cool addon.
In my case, I have a slug column on a model for which I would like to use the slug fieldtype. Obviously, I can just change the fieldtype in the blueprint but I thought it would be nice if it would just generate the blueprints accordingly based on the field name.
If you think this is too opinionated, feel free to just reject the PR. It was a quick win for me, so I thought I would open the PR and leave it up to you.
=> Use Slug as Fieldtype if Column Is Named Slug

docs/installation.md, docs/resources.md, src/Data/AugmentedModel.php, src/Data/HasAugmentedInstance.php, src/Resource.php, src/Routing/RoutingModel.php, src/Runway.php, src/Search/Searchable.php, src/ServiceProvider.php, src/Traits/HasRunwayResource.php, tests/TestCase.php
This pull request introduces the requirement for developers to pull in the `HasRunwayResource` trait into their Eloquent models being used by Runway.
For the longest time, I've wanted to avoid developers needing to add any kind of trait/base class to Eloquent models in the case of simplicity.
The result of this has meant features like GraphQL, routing & search have needed to be hacked together with proxy classes, like `RoutingModel` which sit in-between the feature and the Eloquent model.
After looking into #252, I've realised that we probably do need to add a trait to Eloquent models. Not only to fix that bug but it'll help us to make Runway cleaner & should reduce confusion when I/other developers look at the code 😅
Alongside introducing the requirement for the traits, this PR also does …
=> [5.x] Model Trait

src/Http/Controllers/ResourceController.php
This is needed so when you've joined something and there are duplicated columns you won't get the `Integrity constraint violation` error as the table will be prefixed.
An example is this model on top of a Magento 2 database to get all the manufacturers:
```
class AttributeOptionValue extends Model
{
protected $table = 'eav_attribute_option';
protected $primaryKey = 'option_id';
protected static function booting()
{
static::addGlobalScope(function (Builder $builder) {
$builder
->select('eav_attribute_option.option_id AS option_id')
->addSelect('eav_attribute_option.sort_order')
->addSelect('admin_value.value AS value_admin')
->selectRaw('IFNULL(store_value.value, admin_value.value) AS value_store')
->leftJoin('eav_attribute_option_value AS admin_value', function ($join) { …
```
=> Qualify the routeKey when querying

src/Resource.php
This pull request adds a `config` method to the `Resource` class which allows you to grab any of the values from your Runway configuration array.
You can simply access anything you want like so:
```php
\App\Models\Article::class => [
// ...
'blah' => 'blahblah',
],
```
```php
$resource = Runway::findResource('article');
$resource->config()->get('blah'); // returns "blahblah"
```
=> [5.x] Add `config` method to resource

resources/js/components/Fieldtypes/HasManyRelatedItem.vue, resources/js/components/Fieldtypes/Relationship/RelationshipFieldtype.vue, resources/js/components/Fieldtypes/Relationship/RelationshipTableMode.vue, src/Fieldtypes/BaseFieldtype.php, src/Fieldtypes/HasManyFieldtype.php, src/Http/Controllers/ResourceController.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/TestCase.php, tests/__fixtures__/database/migrations/2020_12_12_220453_create_posts_table.php
This pull request implements #228, allowing for re-ordering of items in the Has Many fieldtype. This feature will work both in the default (stack) mode and in Table mode.
This feature has been built originally for v4.x (because it's where we need it now) but I'll port it for v5.x in the next couple of days.
To enable this feature, you'll need to toggle 'Reorderable?' and set a 'Order Column' so Runway knows where to persist the ordering.
```yaml
- handle: lessons
field:
resource: lesson
create: true
display: Lessons
type: has_many
icon: has_many
listable: hidden
instructions_position: above
visibility: visible
always_save: false
mode: table
reorderable: true
order_column: sort_order
```
=> Re-ordering on Has Many fieldtype

src/GraphQL/ResourceType.php
This pull request fixes an issue where some values would error out when being fetched using the GraphQL API. This was happening due to Runway not augmenting values before returning them back to the GraphQL package.
This fix will do for now and I'll open another PR shortly to hopefully make GraphQL mirror entries in Statamic Core a little better.
=> Fix GraphQL not resolving entries

src/GraphQL/ResourceType.php, src/Traits/HasRunwayResource.php
This pull request refactors the code I introduced in previous PR, #260.
As we now have the `HasRunwayResource` trait on Eloquent models, we can devolve to the value/query builder stuff on there which is provided by the `ResolvesValues` trait.
=> [5.x] Refactor what I introduced in #260

src/Fieldtypes/BaseFieldtype.php, src/Tags/RunwayTag.php, tests/Tags/RunwayTagTest.php
This pull request adds a new `select` parameter to the Runway tag to allow you to improve performance by only using certain columns.
```antlers
{{ runway:posts select="id,title" }}
{{ title }} - {{ id }} 
{{ description }} 
{{ /runway:posts }}
```
=> Add select parameter to Runway tag

src/Fieldtypes/BelongsToFieldtype.php, src/Resource.php
This pull request allows for overriding the Eloquent relationship names for Belongs To & Has Many fields.
By default, Runway will take the field's handle and attempt to do some *magic* to convert it into a relationship name (the name of the relationship method in the Eloquent model).
However, in some cases this logic may fail. For example, if the field handle is completely different from the relationship name, you'd end up seeing an error like in #268.
This is only really needed in the case of the Belongs To fieldtype since the field will be the column name but the relationship method could be different. In the case of the Has Many fieldtype, the field will use the relationship name.
Fixes #268
=> Belongs To Fieldtype: Allow overriding Eloquent relationship names

resources/js/components/Listing/RunwayListing.vue, src/Http/Controllers/ResourceController.php, src/Http/Controllers/ResourceListingController.php, src/Query/Scopes/Filters/Fields.php, src/ServiceProvider.php
This pull request enables filtering on the Runway Listing Table. 
By default, this allows you to filter by field values. However, you can create your own filters that are scoped to Runway resources like so:
```php
public function visibleTo($key)
{
return $key === 'runway';
}
```
=> Enable filters on Runway Listing

package.json, resources/js/components/Listing/DataListFilters.vue, resources/js/components/Listing/RunwayListing.vue, src/Query/Scopes/Filters/Fields.php
This pull request attempts to fix an issue where Runway's new "Fields" filter (introduced in #278) was breaking the "Fields" filter in the entry listing table, amongst others.
This was happening due to the handles of both "fields" filters clashing. Runway was overriding the Statamic one, which meant the Runway fields filter worked but the Entry listing fields filter didn't.
This PR fixes the issue by making Runway use the handle `runway-fields` instead of `fields`. 
However, this causes an issue with the `DataListFilters` component in Statamic since the handle `fields` is [hard-coded](https://github.com/statamic/cms/blob/4.x/resources/js/components/data-list/Filters.vue#LL154C1-L155C1) in a few places.
So, I've had to make a copy of that component specifically for use in Runway's Listing …
=> Attempt to fix "Fields" filter

docs/fieldtypes.md, src/Fieldtypes/HasManyFieldtype.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/TestCase.php, tests/__fixtures__/database/migrations/2023_06_16_123456_create_post_author_table.php
In #259, you could configure a `order_column` which would be the column the sort order would be persisted to when saving a HasMany fieldtype.
However, this didn't cover the case where you might be using pivot tables with a Many to Many relationship. This pull request fixes that by implementing the re-orderable / sort column logic for relationships using pivot tables. 
Fixes #287.
=> Allow for 'sort order' to be persisted on pivot tables

src/Fieldtypes/BaseFieldtype.php, tests/Fieldtypes/BelongsToFieldtypeTest.php
This pull request fixes an issue where the `getIndexItems` method on the `BaseFieldtype` class wasn't using the [ordering config setting](https://runway.duncanmcclean.com/resources#content-ordering) from Runway's config file.
=> Fix `BaseFieldtype@getIndexItems` method not respecting configured ordering

src/Data/AugmentedModel.php
This pull request fixes an issue where `{{ url }}` was not available when looping through search results. Fixes #314.
=> [5.x] Fix `{{ url }}` in search results

src/Query/Scopes/Filters/Fields.php
This pull request fixes an issue where appended attributes would appear in the dropdown of Fields when using the "Fields" filter in the Control Panel.
Filtering by appended attributes won't work because they're not *real* columns in the database that can be queried (at least, most of the time!), so you'll receive an error. So, this PR will filter out any fields that use an appended attribute.
Fixes #316
=> [5.x] Ensure appended attributes aren't returned in fields filter

src/Routing/RoutingModel.php, src/Runway.php, src/Search/Searchable.php, src/ServiceProvider.php, src/Traits/HasRunwayResource.php, tests/TestCase.php
This pull request fixes an issue when setting up the Eloquent Driver alongside Runway.
Essentially, when you're in the process of migrating to the Eloquent driver, you change the repositories, then run a vendor:publish command to publish the migrations.
However, when trying to publish the migrations (or run any other artisan commands for that matter), you'd see an error relating to blueprints. This was happening as Runway was trying to "discover" the resources from the configuration file, including looking up its blueprint.
This PR fixes the issue by catching any exceptions when finding blueprints, then ignoring the resource if the app is running in the console.
Fixes #319.
=> [5.x] Fix blueprint error when publishing Eloquent Driver migrations

src/Runway.php
This pull request fixes an error caused by #320, where an early return with no value was causing havoc with the way `->mapWithKeys()` works.
Fixes #322
=> [5.x] Fix early return when no blueprint found & running in the console

src/Http/Controllers/ResourceController.php, src/Http/Requests/StoreRequest.php, src/Http/Requests/UpdateRequest.php, tests/Http/Controllers/ResourceControllerTest.php, tests/TestCase.php, tests/__fixtures__/database/migrations/2020_12_12_220453_create_posts_table.php, tests/__fixtures__/database/migrations/2023_06_16_123456_create_post_author_table.php
This pull request fixes a few validation issues pointed out in #321. A few examples of broken validation logic:
* A validation error wasn't being thrown when using the `before:date_field` validation rule. Now it is!
* Although, I have noticed this validation rule seems to be thrown even when the first date field *is* before the other one. I can replicate on entries so it's a Core issue, not a Runway one.
* Validation errors weren't being thrown for fields inside Bards/Replicators/Grids, now they will be!
Closes #321.
=> [5.x] Fix validation issues

src/Console/Commands/GenerateMigration.php, src/Console/Commands/stubs/create_table_migration.php.stub, tests/Console/Commands/GenerateMigrationTest.php
This pull request updates the `runway:generate-migrations` command to generate migrations using the anonymous class syntax that was introduced in [Laravel 8.37](https://laravel-news.com/laravel-anonymous-migrations).
Addresses #329
=> [5.x] Generate migrations using anonymous class syntax

src/Console/Commands/GenerateMigration.php
This pull request fixes an issue where Runway would try to run the migrations, even if the user said they didn't want to run them.
Fixes #328
=> [5.x] Don't run migrations if the user said not to

src/Console/Commands/GenerateMigration.php
This pull request fixes an issue when trying to generate a migration, based on a blueprint with a custom fieldtype. Runway would previously generate code like this:
```php
$table->('generate_profile');
```
This was happening as Runway didn't know how to map the fieldtype to a database column type. When this happens now, Runway will add a TODO to the migration.
```php
// TODO: Implement `generate_profile` field.
```
Fixes #327
=> [5.x] Add TODO in migration for columns that can't be mapped

resources/js/components/Publish/PublishForm.vue
This pull request fixes an issue where the sidebar on the Runway Publish Form was missing a background. 
This PR also removes a temporary fix in Runway for statamic/cms#8393 now that issue has been resolved.
=> [5.x] Fix sidebar missing background on publish form

src/Resource.php, tests/ResourceTest.php
This pull request adds two configuration options for `singular` & `plural` for those who want to override Laravel's generated singular/plural output of words.
=> [5.x] Add config options for singular/plurals

src/Http/Controllers/ResourceController.php, tests/Http/Controllers/ResourceControllerTest.php
This pull request fixes an issue where Runway would just error out when you went to the edit page of a record that doesn't exist.
=> [5.x] Throw 404 when record does not exist

src/Tags/RunwayTag.php
There are a few other places that use ->paginate() in this repo, but I've decided not to add `->withQueryString()` to them so that this change only impacts the runway tag and nothing else.
For reference, here are the other places I found the paginate method:
- [BaseFieldType.php:124](https://github.com/duncanmcclean/runway/blob/5.x/src/Fieldtypes/BaseFieldtype.php#L124)
- [ResourceListingController.php:65](https://github.com/duncanmcclean/runway/blob/5.x/src/Http/Controllers/ResourceListingController.php#L65)
- [GraphQL/ResourceIndexQuery.php:L47](https://github.com/duncanmcclean/runway/blob/5.x/src/GraphQL/ResourceIndexQuery.php#L47-L52)
Fixes #349
=> [5.x] Preserve Query Strings In Runway Tag

src/Tags/RunwayTag.php
This pull request fixes the issue that #350 previously tried to fix, where query parameters weren't being retained in the pagination links. 
I just needed to move the `->withQueryString()` method to the other paginator which seemed to do the trick.
Closes #349.
=> [5.x] Ensure query parameters are retained in pagination links

resources/views/index.blade.php
This pull request changes the empty state for the resource index table: an empty listing table will show instead an old empty state.
I only realised the empty state was old after seeing statamic/cms#8787 pop up.
=> [5.x] Show listing table instead of old empty state

src/Http/Controllers/ResourceController.php, tests/Http/Controllers/ResourceControllerTest.php, tests/TestCase.php
Need to re-open #336.
New use case is that I need a field to be **not** saved **and** editable in the CP. Using `visibility:computed` means that the field is not editable in the CP.
=> [5.x] Don’t save fields with `save` set to false

src/Http/Controllers/ResourceListingController.php
If you use `items` in here you don't get the imported fields, if you use `fields()` you do.
=> [5.x] Use fields not items

composer.json, phpunit.xml, tests/Data/AugmentedModelTest.php, tests/Fieldtypes/BelongsToFieldtypeTest.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/Http/Controllers/ResourceControllerTest.php, tests/Http/Controllers/ResourceListingControllerTest.php, tests/ResourceTest.php, tests/Routing/FrontendRoutingTest.php, tests/Routing/ResourceRoutingRepositoryTest.php, tests/RunwayTest.php, tests/Tags/RunwayTagTest.php, tests/TestCase.php, tests/UpdateScripts/ChangePermissionNamesTest.php, tests/UpdateScripts/RunsUpdateScripts.php, tests/__fixtures__/app/Models/Author.php, tests/__fixtures__/app/Models/Post.php, tests/__fixtures__/config/runway.php, tests/__fixtures__/database/factories/AuthorFactory.php, tests/__fixtures__/database/factories/PostFactory.php
This pull request tidies up the Runway test suite in preparation for v6 development.
Some of the changes:
- Moved the Eloquent models out of the `TestCase` file and into their own files.
- Moved the Runway config out of the `TestCase` file and into its own file.
- Replaced the previous `postFactory` and `authorFactory` methods with model factories
- Swapped out `assertSame` for `assertEquals` (dunno why, I like equals right now 🤷‍♂️ )
- Removed a PHPUnit warning that complained about "tests with no assertions"
=> [6.x] Tidy up tests

src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/Traits/HasListingColumns.php, src/Resource.php, tests/Fieldtypes/BelongsToFieldtypeTest.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/ResourceTest.php, tests/__fixtures__/config/runway.php
This pull request refactors Runway gets fields from a resource's blueprint.
Previously, Runway used the `$blueprint->fields()->items()` method which returned arrays for each of the fields. The `items` method also meant fields imported from fieldsets weren't returned.
Now, with this PR, Runway uses the `$blueprint->fields()->all()` method which means we can take advantage of the `Field` object and include any fields imported from fieldsets.
=> [6.x] Refactor how we get blueprint fields

resources/views/create.blade.php, resources/views/edit.blade.php, resources/views/index.blade.php, routes/cp.php, src/Fieldtypes/BaseFieldtype.php, src/Fieldtypes/HasManyFieldtype.php, src/Http/Controllers/ResourceActionController.php, src/Http/Controllers/ResourceController.php, src/Http/Controllers/ResourceListingController.php, src/Http/Requests/CreateRequest.php, src/Http/Requests/EditRequest.php, src/Http/Requests/IndexRequest.php, src/Http/Requests/StoreRequest.php, src/Http/Requests/UpdateRequest.php, src/Http/Resources/ResourceCollection.php, src/ServiceProvider.php, src/Traits/HasRunwayResource.php, tests/Http/Controllers/ResourceControllerTest.php, tests/Http/Controllers/ResourceListingControllerTest.php
This pull request makes two changes:
* It refactors the search query used in Runway's listing tables to use a query scope (which can be over-ridden, if needed).
* Configures route binding for resources
=> [6.x] Refactor listing queries & use route binding for resources

.github/workflows/tests.yml
This pull request adds support for PHP 8.3, due to be released on the [23rd November](https://stitcher.io/blog/new-in-php-83).
=> [6.x] PHP 8.3 Support

src/Data/AugmentedModel.php, src/Fieldtypes/BaseFieldtype.php, src/GraphQL/ResourceIndexQuery.php, src/Http/Controllers/ResourceController.php, src/Http/Controllers/ResourceListingController.php, src/Http/Controllers/Traits/PreparesModels.php, src/Http/Resources/ResourceCollection.php, src/Query/Scopes/Filters/Fields/Models.php, src/Resource.php, src/Tags/RunwayTag.php, tests/ResourceTest.php
This pull request renames the `eagerLoadingRelations` method to `eloquentRelationships`.
If you were previously overriding the "eager loaded relationships" in your resource's config array, you should change the key from `with` to `relationships`:
```php
\App\Models\Product::class => [
// ...
// Previously...
'with' => ['tags', 'manufacturer'],
// Now...
'relationships' => ['tags', 'manufacturer'],
],
```
=> [6.x] Rename `eagerLoadingRelations` method

docs/rest-api.md, src/Data/AugmentedModel.php, src/Http/Controllers/ApiController.php, src/Http/Controllers/RestApiController.php, src/Http/Resources/ApiResource.php, src/ServiceProvider.php, src/Traits/HasRunwayResource.php, tests/Http/Controllers/ApiControllerTest.php, tests/TestCase.php
This PR brings REST Api support to Runway.
Ensure the API is enabled, then opt into any resources you want in `statamic.api.resources` under a `runway` key:
```php
'resources' => [
'collections' => true,
'navs' => false,
'taxonomies' => false,
'assets' => false,
'globals' => true,
'forms' => false,
'users' => false,
'runway' => [
'users' => ['allowed_filters' => ['name']],
],
],
```
Then your resource list should be available at `/api/runway/{resource}`
To do:
=> [6.x] REST API support

routes/cp.php, src/Http/Controllers/CP/ResourceActionController.php, src/Http/Controllers/CP/ResourceController.php, src/Http/Controllers/CP/ResourceListingController.php, src/Http/Controllers/CP/Traits/HasListingColumns.php, src/Http/Controllers/CP/Traits/PreparesModels.php, src/Http/Requests/CP/CreateRequest.php, src/Http/Requests/CP/EditRequest.php, src/Http/Requests/CP/IndexRequest.php, src/Http/Requests/CP/StoreRequest.php, src/Http/Requests/CP/UpdateRequest.php, tests/Actions/DeleteModelTest.php, tests/Fieldtypes/BelongsToFieldtypeTest.php, tests/Http/Controllers/CP/ResourceControllerTest.php, tests/Http/Controllers/CP/ResourceListingControllerTest.php
This pull request moves Control Panel controllers into their own `CP` directory, just to keep things organised now we have both API & Control Panel controllers.
=> [6.x] Move Control Panel controllers

resources/js/components/Publish/PublishForm.vue, src/Actions/DuplicateModel.php, src/ServiceProvider.php, tests/Actions/DuplicateModelTest.php
This pull request implements a new "Duplicate" action for Eloquent models, as requested in #346.
=> [6.x] "Duplicate" action for models

docs/control-panel.md, docs/kb-articles/multisite.md, docs/resources.md, resources/js/components/Publish/PublishForm.vue, resources/views/edit.blade.php, routes/cp.php, src/Fieldtypes/BaseFieldtype.php, src/Fieldtypes/HasManyFieldtype.php, src/Http/Controllers/ApiController.php, src/Http/Controllers/CP/ResourceController.php, src/Http/Resources/ResourceCollection.php, src/ServiceProvider.php, src/Tags/RunwayTag.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/Http/Controllers/ApiControllerTest.php, tests/Http/Controllers/CP/ResourceControllerTest.php, tests/Tags/RunwayTagTest.php
This pull request changes the terminology Runway uses to refer to records/rows/items/models in the database.
Previously, they've been referred to as "records". However, to simplify things, they're now referred to as "models".
=> [6.x] Change "Record" terminology to "Model"

src/Data/AugmentedModel.php, src/Search/Searchable.php, tests/TestCase.php
This pull request fixes an issue relating to supplements & search.
It ensures `$supplements` is always an empty `Collection` & ensures that we're passing in a collection, rather than an array to the `AugmentedModel@supplement` method.
Fixes #376.
=> [5.x] Fix search supplements

src/Http/Controllers/ResourceController.php
This pull request fixes an issue where Runway wasn't passing the Eloquent model as the "parent" into the fields when on publish form pages.
The `parent` can be helpful when developing custom fieldtype as it provides some context about the "thing" thats being edited.
Fixes #379.
=> [5.x] Fix fields parent not being passed on publish forms

src/Http/Controllers/CP/ResourceController.php, src/Http/Controllers/CP/Traits/PreparesModels.php
This pull request fixes an issue where Runway wasn't passing the Eloquent model as the "parent" into the fields when on publish form pages.
The `parent` can be helpful when developing custom fieldtype as it provides some context about the "thing" thats being edited.
Mirrors #381 but for v6.
=> [6.x] Ensure parent is passed into fields in publish forms

src/Http/Controllers/ResourceController.php
This pull request fixes an issue when using Laravel's [`unique`](https://laravel.com/docs/master/validation#rule-unique) validation rule. 
Runway didn't provide the model's ID as a "replacement" value so the current model couldn't be excluded from the validation.
Fixes #385.
=> [5.x] Fix `unique` validation rule

phpunit.xml, src/Actions/DeleteModel.php, src/Fieldtypes/BaseFieldtype.php, src/Http/Requests/EditRequest.php, src/Http/Requests/UpdateRequest.php, src/Http/Resources/ResourceCollection.php, src/Policies/ResourcePolicy.php, tests/Policies/ResourcePolicyTest.php
The `ResourcePolicy` needs the actual model, in case there's logic that requires it.
=> [5.x] Pass model to the policy

src/Resource.php, tests/ResourceTest.php
Fixes #392. Currently, if you mark a field as `hidden`, the second qualifier in the `listableColumns` method of `Resource.php` (noted below) causes it to be rejected. That is, it does not show up in the "column picker" of the control panel's index view:
```php 
/**
* Returns an array of column handles that are marked as listable.
*/
public function listableColumns(): array
{
return $this->blueprint()->fields()->items()
->reject(function ($field) {
return isset($field['import'])
// ❌ This PR removes the following line, to avoid rejecting hidden fields:
|| (isset($field['field']['listable']) && $field['field']['listable'] === 'hidden') 
|| (isset($field['field']['listable']) && $field['field']['listable'] === false);
})
->pluck('handle')
->toArray();
}
```
This PR makes "column …
=> [5.x] Bug: Missing hidden fields in listableColumns

src/Resource.php, tests/ResourceTest.php
This pull request fixes an issue I noticed while spinning up a fresh Runway install. 
The fields in the blueprint builder are automatically set to `listable: hidden` and if you visit the listing table without any visible columns, you'd get an error.
This should hopefully fix that issue and mirror the changes made in #393 for v5.x.
=> [6.x] Fix listable fields state

src/Resource.php
Fixes an issue with nav icons not displaying. Currently, v6 is using a `has` method both for the initial check _**and**_ to generate the actual return value, so all icons come back as `1`, which of course isn't a valid icon string.
=> [6.x] Fix nav icons not displaying

src/Http/Controllers/ResourceController.php, tests/TestCase.php
This pull request passes along the Model ID in the `values` that get passed along to the publish form so it exists in the Vuex store.
Fixes duncanmcclean/simple-commerce#966
=> [5.x] Include Model ID in Publish Form values

src/Data/AugmentedModel.php, tests/Data/AugmentedModelTest.php, tests/__fixtures__/app/Models/Post.php
This pull request fixes an issue where model accessors aren't being augmented after the augmentation changes in #354.
Fixes #404.
=> [6.x] Fix model accessors not being augmented

src/Fieldtypes/BaseFieldtype.php
This pull request fixes an issue when trying to save models via Runway's Relationship Fieldtypes. 
After changes to the way publish form actions worked in #400, I didn't tweak `$formComponentProps` in the `BaseFieldtype` for the renamed prop to be passed along to the "inline publish form".
Fixes #406.
=> [6.x] Fix saving models in relationship stacks

README.md, docs/blueprints.md, docs/index.md
Blueprints: Added Note to call attention to the accessor being defined as a public function, which differs from the Laravel docs example.
Index & Readme: Changed products to product in the example to reflect the singular nature of the handle for other resources used in the documentation.
=> [6.x] Documentation Changes for Blueprints, Index, and Readme

src/Fieldtypes/HasManyFieldtype.php
This pull request fixes an issue when saving the HasMany fieldtype, where any changes made wouldn't actually be saved.
In #375, we changed the name of the route parameter for models from `record` to `model`. It looks like the change was missed here.
=> [6.x] Fix saving Has Many fieldtype

src/Console/Commands/RebuildUriCache.php
This pull request adds a progress bar to the `runway:rebuild-uri-cache` command to make it look a little more beautiful.
=> [6.x] Add progress bar to rebuild URI cache command

src/Fieldtypes/BaseFieldtype.php
This pull request fixes an issue where model MorphToMany relationships aren't being augmented after the augmentation #412
=> [6.x] Fix model MorphToMany relationships not being augmented.

resources/js/components/Publish/PublishForm.vue
This pull request fixes an issue where Has Many relationship fields were being overwritten unintentionally when the publish form was opened in an inline stack.
It looks like this was caused by refactoring in 54c79d6, where `&&` was swapped with a `||` causing the pre-filling logic to be run when it shouldn't be.
Fixes #426.
=> [6.x] Fix value in HasMany fieldtype being overwritten when opened in inline publish form

src/Routing/Routable.php, src/Routing/Traits/RunwayRoutes.php
This pull request fixes an issue where you'd end up in an infinite loop when getting/setting the `slug` attribute on a model with the `RunwayRoutes` trait.
This was happening because Runway's `RunwayRoutes` trait contains a [`slug()`](https://github.com/statamic-rad-pack/runway/blob/6.x/src/Routing/Traits/RunwayRoutes.php#L30) method (which is required by Statamic's routing contracts).
The `slug` method attempts to get the current slug for the model, using Eloquent's [`getAttribute`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L429) method. Since, it can't find a value for `slug` on the model, it finds that there's a `slug()` method on the model and tries to use that instead. That's where the infinite loop happens.
This PR …
=> [6.x] Fix infinite loop caused by slug method

src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/CP/ResourceListingController.php, tests/Fieldtypes/BelongsToFieldtypeTest.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/Http/Controllers/CP/ResourceListingControllerTest.php, tests/__fixtures__/app/Models/Author.php, tests/__fixtures__/app/Models/Post.php
This PR moves the orderBy clause to after runwayListing has been run, and make it conditional on whether an orderBy clause already exists.
Let me know where to make a test for this as I cant see any coverage of the scopes?
Replaces https://github.com/statamic-rad-pack/runway/pull/433
=> [6.x] Allow runwayListing scope to modify the order

src/Data/AugmentedModel.php, src/Fieldtypes/BaseFieldtype.php, src/Tags/RunwayTag.php
This pull request refactors how Eloquent Relationships are augmented to improve performance and prevent as many duplicate queries, like seen in #430. 
Changes include:
* Instead of a `HasMany`/`BelongsTo` relationship instance being passed to the augmentation methods, we now pass an `Eloquent\Collection` instance. 
* Essentially, we're now doing `$model->relationship` instead of `$model->relationship()`. This change also lets us take advantage of eager loading for the related models.
* I've refactored the augmentation methods in the `BaseFieldtype` to simplify it, now it only needs to accept an `Eloquent\Collection` or an array of IDs (in the case the fieldtype is being used on entries). 
* The `runwayUri` relationship no longer gets augmented.
* There's no reason for the `runwayUri` …
=> [6.x] Improve augmentation of relationships

src/Http/Controllers/CP/ResourceListingController.php, tests/Http/Controllers/CP/ResourceListingControllerTest.php
This [change](https://github.com/statamic-rad-pack/runway/pull/434/commits/0321d67eba5b65089926e1f52df56117aa49fa82) reverted some of the logic for handling user selected sorting.
This PR brings it back.
Closes #437
=> [6.x] Bring back handling user selection when there is no other orderby

src/Fieldtypes/BaseFieldtype.php
This pull request fixes an issue where `$values` was an Eloquent `Model` instance. However, when it was being converted into a Illuminate `Collection`, it ended up turning into an array like this:
```
[
'id' => 1,
'name' => 'John Doe',
'email' => 'john.doe@example.com',
'data' => ['foo' => 'bar']
]
```
This array was then passed in as separate items into the `->map` which ended up causing issues. By adding an `Arr::wrap`, single items, like the `Model` will now be wrapped in an array before going into the Illuminate Collection.
Fixes duncanmcclean/simple-commerce#1016
=> [6.x] Wrap values when getting augmentable models

src/ServiceProvider.php
Prior to this PR, the permission set for Runway resources (eg, as seen when creating a new `role`) was grouped in with **Miscellaneous**, resulting in a duplicate header and no Runway section. This change updates the `registerPermissions` method in Runway's service provider, by swapping the trailing `->group` call for a `::group` closure/wrapper, as outlined in **[Statamic's docs](https://statamic.dev/extending/permissions#groups)**.
=> [6.x] Fix permissions grouped under "Miscellaneous"

src/Fieldtypes/BaseFieldtype.php
This pull request follows on from #440, fixing an issue where `Collection` instances would be wrapped into an array with a single item.
This doesn't match up to an existing issue but something I just noticed while testing something else.
=> [6.x] Fix issue when wrapping values for augmentation

src/Console/Commands/GenerateMigration.php, tests/Console/Commands/GenerateMigrationTest.php
This pull request attempts to fix the flaky tests in `GenerateMigrationTest`.
The failures are down to the timestamp in the migration filename being slightly different to the filename expected. I've tried to fix it before with `TestTime` but it didn't end up working. Hopefully this is the time I can fix it for good 🤞
=> [6.x] Fix flaky failing tests

src/Console/Commands/GenerateBlueprint.php
This pull request fixes an issue with the `runway:generate-blueprint` command where decimal and float columns were being generated as `floatval` fields, when they should have been `float` fields.
Fixes #459.
=> [6.x] Fix `runway:generate-blueprint` command generating fields with incorrect fieldtype

src/ServiceProvider.php
This pull request aims to fix an issue where you'd experience a `QueryException` when running `composer dump-autoload`, due to the `blueprints` table having not been migrated yet.
This error is reproducible when installing the [Eloquent Driver](https://github.com/statamic/eloquent-driver) or setting up a fresh project which uses the Eloquent Driver.
The `blueprints` table didn't exist so when Runway tried to register its blueprint namespace, it failed. 
This PR attempts to fix the issue by catching the `QueryException` when registering the blueprint namespace to avoid the error showing up on fresh installs / deployments.
Fixes #465
=> [6.x] Catch `QueryException` when registering Runway's blueprint namespaces

composer.json, src/Console/Commands/GenerateBlueprint.php, src/GraphQL/ResourceType.php, tests/Console/Commands/GenerateBlueprintTest.php
This pull request drops our `doctrine/dbal` dependency, in favour of provided Laravel methods.
=> [7.x] Drop `doctrine/dbal` dependency

src/Http/Controllers/CP/ResourceActionController.php
Closes #469. After this change, models are essentially eager-loaded, using the `findMany` method inside `getSelectedItems`. See #469 for a before, and here's an after (see query counter in the debugbar):
This also has (what I would consider) an added benefit, by returning an _eloquent_ collection, instead of a generic collection. Allows you to do some handy things within the `Action` class itself, like `$items->load('anotherRelation')`. Wanted to mention this in case it impacts anything downstream that I'm unaware of, but should just be a net-positive since the eloquent collection class extends the base collection class. 👍
Let me know if we need to tweak anything, here!
=> [6.x] Fix N+1 queries in ResourceActionController

src/Http/Resources/CP/Models.php
This pull request prevents appended attributes from being sorted/ordered in listing tables.
Fixes #471.
=> [6.x] Appended attributes shouldn't be sortable in listing tables

src/ServiceProvider.php
=> [6.x] Fix runway resources getting added to the wrong section when using other languages than English

src/Exceptions/EmptyBlueprintException.php, src/Http/Controllers/CP/Traits/HasListingColumns.php
This pull request improves the error handling around visiting the resource listing page in the CP for a resource with an empty blueprint.
Previously, when you visited a resource listing page with an empty blueprint, you'd get an error message.
=> [6.x] Throw exception when blueprint is empty

resources/js/components/Publish/PublishForm.vue, resources/views/edit.blade.php, src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/CP/ResourceController.php, src/Traits/HasRunwayResource.php
This pull request gives models the concept of "references", which are used by entries/terms/assets/etc to be a unique identifier of _things_ in Statamic.
We're then passing the `reference` down to the publish container, so it's available to be checked against in my recursive editing fix in core.
Related: statamic/cms#10012
=> [6.x] Pass `reference` through to publish containers

composer.json, resources/views/index.blade.php, src/Exceptions/EmptyBlueprintException.php, src/Exceptions/TraitMissingException.php, src/Ignition/Solutions/AddTraitToModel.php, src/Runway.php, src/ServiceProvider.php
This pull request makes some improvements to how Runway's exceptions are handled, including adding Ignition solutions.
When you add an Eloquent Model to the `runway.php` config file but forget to add the `HasRunwayResource` trait, you'll now be able to add straight from the exception page by clicking the "Add trait" button.
When you try to view a resource's listing page **without** any fields in its blueprint, you'll see an exception prompting you to add some.
With these improvements, you're now able to click the "Edit blueprint" link to go directly to the blueprint builder to start adding fields.
=> [7.x] Improve exception handling

config/runway.php, database/migrations/2021_05_04_162552_create_runway_uris_table.php, docs/frontend-routing.md, src/Routing/RunwayUri.php
This pull request adds a new `uris_table` configuration option, allowing developers to customize the name of the table used for the "URI Cache".
Related: #490
=> [7.x] Add ability to customize URIs table name

tests/Actions/DeleteModelTest.php, tests/Actions/DuplicateModelTest.php, tests/Actions/PublishTest.php, tests/Actions/UnpublishTest.php
This pull request adds the `PreventsSavingStacheItemsToDisk` trait to tests which create entries, to prevent files being left over in the filesystem after running the test suite.
=> [7.x] Add `PreventsSavingStacheItemsToDisk` trait to tests

src/Routing/Routable.php
This pull request fixes an issue when getting the Redirect URLs for models, in Runway's `Routable` trait.
I ran into this error in #509, when calling `->absoluteUrl()` on a model.
=> [7.x] Fix errors when getting redirect URL for model

resources/js/components/Publish/PublishForm.vue, resources/views/create.blade.php, resources/views/edit.blade.php
This pull request improves the page `<title>`s on Publish Form pages.
Previously, they were just "Create Post" or "Edit Post". However, this PR makes them more like entries and changes them to "Post Title < Posts".
=> [7.x] Improve page titles

resources/js/components/Publish/PublishForm.vue
This pull request fixes an issue where an empty sidebar would be rendered, even when the blueprint contains no "sidebar" tab.
=> [7.x] Only show the sidebar when it's needed

src/Fieldtypes/HasManyFieldtype.php
This pull request fixes an issue with the Has Many fieldtype where the Create/Link buttons wouldn't be displayed, when the fieldtype is used outside of a Runway context (eg. in an entry). 
It _might_ have been caused by statamic/cms#10272, although I haven't confirmed that.
Fixes #516.
=> [7.x] Fix broken Has Many fieldtype when used outside of resources

src/Console/Commands/GenerateBlueprint.php
Closes https://github.com/statamic-rad-pack/runway/issues/523
=> [7.x] Support `int` and `timestamp` column types when generating blueprints

src/Http/Controllers/CP/Traits/HasListingColumns.php
This pull request fixes an issue on Runway's listing table, where the `title_field` setting wouldn't take affect if the user has customized the columns being displayed.
Related: #22
=> [7.x] Fix "title field" when columns have been customized

docs/resources.md, src/Fieldtypes/BaseFieldtype.php, src/Http/Controllers/CP/ResourceListingController.php, src/Resource.php, src/Search/Searchable.php, tests/Fieldtypes/BelongsToFieldtypeTest.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/Http/Controllers/CP/ResourceListingControllerTest.php
This PR adds the ability to specify a `search_index` on resources to use a Statamic search index in both the CP field type and the listing view.
Closes https://github.com/statamic-rad-pack/runway/discussions/501
=> [7.x] Allow search_indexes on resources

composer.json, src/Exceptions/TraitMissingException.php, src/Ignition/SolutionProviders/TraitMissing.php, src/Ignition/SolutionProviders/TraitMissingException.php, src/Ignition/Solutions/AddTraitToModel.php, src/Resource.php, src/Routing/ResourceResponse.php, src/ServiceProvider.php
This pull request fixes an issue with the "runnable solution" for the exception when the `HasRunwayResource` trait is missing from a model.
I'm not entirely sure *when* it broke - it may/may not have been caused by Ignition's recent refactor - but this PR fixes it and adjusts the minimum version of `spatie/ignition` that should be required.
=> [7.x] Fix Ignition Runnable Solutions

resources/js/components/Publish/PublishForm.vue, src/Http/Controllers/CP/ResourceController.php, tests/Http/Controllers/CP/ResourceControllerTest.php
This pull request fixes an issue when saving inline publish forms, where you'd run into a database error due to it trying to save an array as the ID of a relationship.
It seems like this issue was being caused by some legacy code handling around inline publish forms, related to the "Table" mode which was dropped in v6 (#360).
I believe this code was how it re-populated relationship fields in the table after saving a model. Since we don't need it anymore, removing it fixes the issue.
Fixes #546.
Related: #544.
=> [7.x] Fix inline publish forms

resources/js/components/Publish/PublishForm.vue
This pull request fixes an issue when creating models via the Has Many / Belongs To fieldtype, where after saving the model in the inline publish form, it would redirect you to the model's edit page, instead of keeping you on the same page, like it should.
=> [7.x] Prevent redirect when creating model via inline publish form

src/Exceptions/PublishedColumnMissingException.php, src/Resource.php
This pull request prevents an infinite loop from happening when trying to load the listing table for a resource w/ publish states enabled, but without an actual `published` column in the database yet.
=> [7.x] Prevent infinite loop when published column is missing

resources/js/components/Publish/PublishForm.vue, src/Http/Controllers/CP/ResourceController.php, src/Ignition/Solutions/AddTraitToModel.php, src/Relationships.php, src/Resource.php, src/Routing/ResourceResponse.php, src/ServiceProvider.php, src/UpdateScripts/AddManagePublishStatesPermission.php, src/UpdateScripts/AddManagePublishStatesPermissionToRoles.php, tests/UpdateScripts/AddManagePublishStatesPermissionTest.php
Matching the `canManagePublishState` from core and replicating this PR: https://github.com/statamic/cms/pull/10424
=> [7.x] Add Publish State permission

resources/js/components/Publish/PublishForm.vue
This pull request copies the fix from statamic/cms#10381 into Runway, since the publish form logic is pretty similar.
=> [5.x] Fix dirty state after entry action or revison publish

src/Data/HasAugmentedInstance.php, src/Ignition/Solutions/AddTraitToModel.php, src/Relationships.php, src/Resource.php, src/Routing/ResourceResponse.php, tests/Tags/RunwayTagTest.php
This PR adds an `augmented` hook to Runway resources, similar to the functionality in core: https://github.com/statamic/cms/pull/9625
My use case is this will let us track Runway resources in our Cache Tracker add-on.
=> [7.x] Add augmentation hook

src/Fieldtypes/BelongsToFieldtype.php, src/Fieldtypes/HasManyFieldtype.php, tests/Fieldtypes/BelongsToFieldtypeTest.php
This pull request fixes an issue with GraphQL and Runway's Belongs To & Has Many fieldtypes, when the fields are added to an entry blueprint. 
Fixes #561.
=> [7.x] Fixed error when accessing Runway's fieldtypes via GraphQL

src/Resource.php
Hi there! My problem was the following:
My relationship method names are - rather old fashioned - named in snake case, f.e. "voucher_themes()". As your package tries to guess the right method name, it automatically converts this to "voucherThemes()". 
You have an explicit attribute that can be used for this ("relationship_name") - but in your method the part where this was implemented was followed by the one where it looks for a snake case name and converts it, so the "relationship_name" one is immediately overwritten.
I moved the part where it uses the "relationship_name" to the end of the logic, so if this is used, it will not be overwritten by other logic following it. 
This fixes my problem - but if you like I can dig a bit deeper and rewrite the method so that it checks if the …
=> [7.x] Fix explicit relationship name being overwritten in HasMany relationships

src/Relationships.php, tests/RelationshipsTest.php
This pull request prevents relationship fields set as computed or `save: false` from attempting to save to the model.
Related comment: https://github.com/statamic-rad-pack/runway/issues/572#issuecomment-2253114305
=> [7.x] Prevent saving computed relationship fields

composer.json, src/Data/AugmentedModel.php
This pull request fixes an issue where `protected` model accessors would cause an error (Laravel documents them as `protected`). 
This PR also prevents an error when a mutator exists on a model without an accessor equivelent.
Fixes #573.
=> [7.x] Fix protected model accessors & model mutators without accessor equivelent

src/Resource.php
This pull request fixes an issue where Runway would consider non-text fields, like Asset fields or Entry fields as eligible to be "title fields".
Fixes  #578.
=> [7.x] Don't consider non-text fields eligible for a resource's "title field" 

src/Traits/HasRunwayResource.php
Due to https://github.com/statamic-rad-pack/runway/pull/556, model fields that are json data are removed from the working copy because `$this->getAttribute($field->handle())` returns `null` when the handle is `foo->bar`.
Instead we need to get `foo`.
No tests yet @duncanmcclean but this code does work.
=> [7.x] Fix JSON field revisions

src/ServiceProvider.php
We have [our own package](https://github.com/rapidez/statamic) that uses the runway add-on. We have defined [default Runway resources](https://github.com/rapidez/statamic/blob/master/config/rapidez/statamic.php#L56) in this module. As we're updating our module to be compatible with the latest version of Runway we've come across a problem.
We want to define the blueprints in our module, thus we had the config file. In the latest Runway version, blueprints live in `.yaml` files under the `resources/blueprints/vendor/runway` directory. We'd like to use the `php artisan vendor:publish` command to copy our module defined blueprints to the project. Sadly when running `php artisan vendor:publish` the [Runway service provider](https://github.com/statamic-rad-pack/runway/blob/7.x/src/ServiceProvide …
=> [7.x] Only create the blueprints when not running on console

docs/templating.md, src/Tags/RunwayTag.php, tests/Tags/RunwayTagTest.php
I couldn't find it anywhere in the docs or code. If it already exists or there's another way to quickly count all resources feel free to close. Inspired by the collection:count [tag](https://statamic.dev/tags/collection-count).
```php
Statamic::tag('runway:count')->in('plant')
// or
{{ runway:count in="plant" }}
```
=> [7.x] Add runway:count tag

resources/js/components/resources/View.vue, resources/views/index.blade.php
This pull request fixes an issue with the Listing Table where it wouldn't use the order defined in a custom `runwayListing` query scope.
Fixes #587.
=> [7.x] Fix sorting in listing tables

src/GenerateBlueprint.php, src/Resource.php
Right now, when you add an Eloquent Model to your Runway config and visit that resource in the Control Panel, it'll throw an exception asking you to go to the blueprint and add some fields.
Now, with this pull request, it'll automatically create a blueprint for you and build out the fields based on your database columns. 
You can obviously go in and manualy update the blueprint to add/change/remove any fields.
=> [7.x] Improve handling of empty blueprints

docs/relationships.md
This pull request renames the "Fieldtypes" page to "Relationships" and restructures the page so we have space to go into more detail about relationships other than Belongs To & Has Many.
=> [7.x] Improve relationship docs

composer.json, src/Routing/ResourceResponse.php
This pull request fixes an issue where the `page` variable was missing in Blade templates, due to Statamic only adding it when we pass the model as the view's `cascadeContents`.
Fixes #584.
Related: statamic/cms#10759.
=> [7.x] Add missing `page` variable for Blade templates

src/Fieldtypes/BaseFieldtype.php
This might fix #598 . When i add this check it returns the page without errors and the runway resource that does not exist anymore will be marked red for the user to delete.
=> [7.x] Return unlink when parent is not set

src/Fieldtypes/BaseFieldtype.php, tests/Fieldtypes/HasManyFieldtypeTest.php
This pull request fixes an issue where an error would occur when using the Has Many fieldtype on an entry blueprint.
Closes #600.
=> [7.x] Fix error with Has Many fieldtype when used on entries

src/Routing/ResourceResponse.php
This pull request fixes an issue where fields weren't being augmented correctly on frontend routes.
This issue was caused by #590, where we started passing the model to `->cascadeContent()` instead of passing the augmented array to `->with()`.
However, this meant that the data on frontend routes wasn't being augmented since [`Cascade::hydrateContent()`](https://github.com/statamic/cms/blob/6db65ff2b820b6c21d8b3c1a88c1d74c5289e981/src/View/Cascade.php#L161C48-L161C59) checks if the data (the Eloquent Model in this case) implements the `Augmentable` interface which models aren't implementing.
Since there's no way for us to add the interface in Runway's traits, we're just passing the augmented data along again to `->with()` which fixes the issue.
Fixes #606.
=> [7.x] Fix augmentation on frontend routes

src/Http/Resources/CP/ListedModel.php
This pull request fixes an issue when linking a related model, when the related model's resource had publish states enabled.
Statamic's [`Selector` Vue component](https://github.com/statamic/cms/blob/c2008b387e91444c66ad74672609edc1210adddb/resources/js/components/inputs/relationship/Selector.vue#L426) checks the `collection.dated` key on items (because it presumes that the only items with publish states are going to be entries). 
So, to make everthing work, we're just returning that key from our resource.
Fixes #612.
=> [7.x] Fix error when linking related model with publish states

src/Http/Resources/CP/ListedModel.php
This pull request fixes an issue with Runway's fieldtypes when used in Select/Typeahead modes, where the select options were missing titles.
Caused by #592.
Fixes #615.
=> [7.x] Fix missing title on fieldtype dropdown options

src/Support/Json.php
Profiling i noticed (in my case) jsJson is called over 10k times in the code, causing wall time to be quite high.
On large strings `json_decode` is a heavy operation, if we perform some simpler string checks we can hopefully reduce some json_decode operations.
once https://www.php.net/manual/en/function.json-validate.php can be used this can further optimise the check since it's what json_decode uses before actually attempting to decode, thus we can skip the decoding itself.
=> [7.x] Minor optimisations on isJson function

src/ServiceProvider.php
This pull request allows for Runway URIs to be warmed as part of Statamic's `static:warm` command.
Related: #603
=> [7.x] Warm Runway URIs as part of the `static:warm` command

src/Support/Json.php
I've seen a couple warnings pop up during development
> LOG.warning: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in vendor/doublethreedigital/runway/src/Support/Json.php on line 18
So we should probably add a check whether we're dealing with a null value as well
=> [7.x] Add check whether value is null

src/Data/AugmentedModel.php, tests/Data/AugmentedModelTest.php, tests/__fixtures__/app/Models/Post.php, tests/__fixtures__/database/factories/PostFactory.php, tests/__fixtures__/database/migrations/2020_12_12_220453_create_posts_table.php
Fixes #627 
Passes the `$value` and `$attributes` values to the models Attributes getter.
=> [7.x] Fix error when augmenting model mutators

src/Http/Controllers/CP/Traits/PreparesModels.php
This pull request fixes an issue where HasMany relationships weren't being resolved if the field handle differed from the `relationship_name`.
For example: 
```yaml
-
handle: shipping_addresses
field:
resource: organization_shipping_address
relationship_name: shippingAddresses
type: has_many
display: 'Shipping addresses'
sortable: false
```
Even though the field handle was the "same" as the relationship name, but slugified, doing `$model->shipping_addresses` wouldn't work.
This PR fixes it by getting the correct relationship name, and calling that attribute instead.
Fixes #624.
=> [7.x] Fix issue where HasMany relationship wasn't being resolved

resources/views/edit.blade.php, routes/cp.php, src/Fieldtypes/HasManyFieldtype.php, src/Http/Controllers/CP/ModelActionController.php, src/Http/Controllers/CP/ResourceActionController.php, src/Http/Controllers/CP/ResourceController.php, tests/Console/Commands/GenerateMigrationTest.php, tests/Fieldtypes/BelongsToFieldtypeTest.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/Http/Controllers/ApiControllerTest.php, tests/Http/Controllers/CP/ModelActionControllerTest.php, tests/Http/Controllers/CP/ModelRevisionsControllerTest.php, tests/Http/Controllers/CP/PublishedModelsControllerTest.php, tests/Http/Controllers/CP/ResourceActionControllerTest.php, tests/Http/Controllers/CP/RestoreModelRevisionController.php, tests/Tags/RunwayTagTest.php
This pull request fixes an error when running resource actions, where code was expecting a `Model` instance to be passed in when it was a `Resource`.
It looks like "resource actions" and "model actions" were sharing the same controller. This PR splits them out to match how Statamic handles collection/entry actions.
I have no idea how resource actions were working in the first place. 🤷‍♂️
Fixes #637.
=> [7.x] Fix error when running resource actions

src/Actions/DuplicateModel.php, tests/Actions/DuplicateModelTest.php, tests/Console/Commands/GenerateMigrationTest.php, tests/Fieldtypes/BelongsToFieldtypeTest.php, tests/Fieldtypes/HasManyFieldtypeTest.php, tests/Http/Controllers/ApiControllerTest.php, tests/Http/Controllers/CP/ModelRevisionsControllerTest.php, tests/Http/Controllers/CP/PublishedModelsControllerTest.php, tests/Http/Controllers/CP/ResourceActionControllerTest.php, tests/Http/Controllers/CP/RestoreModelRevisionController.php, tests/Tags/RunwayTagTest.php, tests/__fixtures__/database/factories/PostFactory.php
This pull request fixes an issue with Runway's "Duplicate" action where it wasn't respecting the "Duplicate" option on fields. Now it does.
Closes #635.
=> [7.x] Respect "Duplicate" toggle on fields

src/Fieldtypes/BaseFieldtype.php
This pull request fixes an issue where Belongs To fields were being saved as arrays, instead of integers/strings, when saved in a non-model context (eg. in an entry blueprint).
Fixes #640.
=> [7.x] Prevent Belongs To fields being saved as an array in entry data

src/Fieldtypes/BaseFieldtype.php
This pull request fixes an issue where unpublished models were being returned when augmenting Runway relationships.
=> [7.x] Only published models should be returned by augmentation

composer.json
This pull request removes the Laravel Prompts dependency from Runway's `composer.json` file, since it's already required by `statamic/cms`.
Closes #646.
=> [7.x] Remove `laravel/prompts` from composer.json

src/Fieldtypes/BaseFieldtype.php
In our situation we have a field "products" in a page builder fieldset, it is a HasMany field that links to the Product runway model. However there's no relationship set on the models so we're getting the error "called to undefined method "products". This way the field will check if the relationship exists before calling the method.
=> [7.x] Check if relationship method exists before calling it

docs/control-panel.md, docs/resources.md, docs/upgrade-guides/v7-to-v8.md, src/Resource.php, src/ServiceProvider.php
This pull request removes the `cp_icon` config option, in favour of customizing the icon via CP Nav Preferences (see https://github.com/statamic/cms/pull/8023).
=> [8.x] Remove `cp_icon` config option

src/Relationships.php
This pull request prevents an error from occurring when the model can't be found in the database. This could have occured if a related model was deleted while the user was on the publish form.
=> [7.x] Prevent error when model can't be found

database/migrations/2021_05_04_162552_create_runway_uris_table.php
This pull request updates the `runway_uris` migration stub, changing the `model_id` column from a `bigInteger` to a `string` in order to allow for models with UUIDs.
=> [8.x] Change `model_id` column on `runway_uris` table to a string

resources/js/components/resources/PublishForm.vue, resources/views/edit.blade.php, src/Http/Controllers/CP/ResourceController.php, src/Http/Resources/CP/Model.php
This pull request adds a status indicator next to titles on model publish forms, similar to how they're displayed on entries:
=> [7.x] Show status indicator on publish form

src/Http/Controllers/CP/Traits/ExtractsFromModelFields.php
Following on from https://github.com/statamic/cms/issues/11333
Fix implemented through runway.
=> [8.x] Fix attributes returning a collection instead of an array

src/Console/Commands/RebuildUriCache.php
Currently, models that have global model scope(s) set up (such as for private or hidden models) won't have their URI rebuilt/cached when this command is run.
This PR adds a simple `->withoutGlobalScopes()` to bypass the scopes while the cache is being rebuilt.
I don't think there are any long term implications against this, but let me know if there are.  Could also just place it behind an option flag if so.
=> [8.x] Add withoutGlobalScopes to Rebuild URI's command

src/Scopes/Status.php
This pull request fixes an issue where Runway would override the "Status" filter from Statamic, preventing it from showing on collection listings.
Fixes #662.
=> [8.x] Fix disappearing status filter on collections 

src/Http/Controllers/CP/Traits/ExtractsFromModelFields.php
This pull request reverts #654 as it caused issues with relationship fields for some projects. The original issue that PR tried to solve can be fixed by using a different cast on the Eloquent model.
Fixes #665.
=> [8.x] Revert "[8.x] Fix attributes returning a collection instead of an array"

docs/resources.md, src/Console/Commands/RebuildUriCache.php, src/Fieldtypes/BaseFieldtype.php, src/GraphQL/ResourceIndexQuery.php, src/Http/Controllers/CP/ModelRevisionsController.php, src/Http/Controllers/CP/PublishedModelsController.php, src/Http/Controllers/CP/ResourceController.php, src/Http/Controllers/CP/ResourceListingController.php, src/Resource.php, src/Routing/RunwayUri.php, src/Search/Provider.php, src/Tags/RunwayTag.php, src/Traits/HasRunwayResource.php
This pull request implements a `runway` query scope, which allows developers to customise the queries executed by Runway.
For example: maybe you want to disable global scopes, or only return models created in the past year.
```php
class YourModel extends Model
{
public function scopeRunway($query)
{
return $query->where('something', true);
}
}
``` 
Under the hood, all query now go through the `Resource::newEloquentQuery()` method.
Related: #669
=> [8.x] Add `runway` query scope

docs/resources.md
Removes extra "->" in Disabling global scopes example
=> [8.x] Fix typo in resources.md

src/Console/Commands/ImportCollection.php, src/Console/Commands/stubs/model-l10.stub, src/Console/Commands/stubs/model.stub
This pull request fixes an issue with the collection importer, where the `getRouteKeyName` method would be added to Eloquent models, even when the slugs weren't enabled on the source collection.
This would cause a 404 when viewing models in the Control Panel.
Related: https://github.com/statamic-rad-pack/runway/discussions/675#discussioncomment-12664400
=> [8.x] Only add `getRouteKeyName` to models when collection uses slugs

src/Resource.php
This pull request fixes an error when attempting to serialize Runway's `Resource` object, which ultimately attempts to serialize a fresh instance of the Eloquent model.
However, since it serialises the fresh instance of the Eloquent model, no attributes are set, so model accessors using the `$attributes` parameter error out:
```php
// app/Models/User.php
protected $appends = ['thingy'];
protected function thingy(): Attribute
{
return Attribute::make(
get: fn (mixed $value, array $attributes) => $attributes['name']
);
}
```
```php
use App\Models\User;
(new User)->toArray();
```
```
Undefined array key "name"
```
To prevent an error when serializing appended attributes on a fresh model, we're now simply returning the model's class name, rather than calling its `toArray()` method.
Fixes …
=> [8.x] Fix error when serializing resources with appended attributes

composer.json, tests/TestCase.php
This pull request requires `spatie/laravel-ray` so we can use Ray during development, without needing to require it globally.
=> [8.x] Require `spatie/laravel-ray` in dev

src/Routing/MorphOneWithStringKey.php, src/Routing/Traits/RunwayRoutes.php
While I was working on the collection importer command, I changed the `model_id` column on the `runway_uris` table from an integer to a string (see #656), allowing imported models to keep their original, string-based UUIDs, preventing broken relationships.
This change worked fine for my locally, as MySQL would cast integers to strings when querying, and vice-versa.
However, this change caused issues with PostgreSQL, which errors when you try and query a string column with an integer:
```
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer
LINE 1: ...from "runway_uris" where "runway_uris"."model_id" in (1, 3, ...
^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```
After …
=> [8.x] Prevent errors from PostgreSQL when querying `runway_uris` table

src/Data/AugmentedModel.php, tests/Data/AugmentedModelTest.php
Currently, if you want to access a nested field on an augmented model, you need to go through the JSON column, like this:
```antlers
{{ meta:rating }}
```
This pull request makes it possible to also access nested fields using their field handles:
```antlers
{{ meta_rating }}
```
Closes #698
=> Improve nested field augmentation

src/Routing/RoutingModel.php, tests/Routing/RoutingModelTest.php
This PR adds a `resource` method on the `RoutingModel` class, allowing for easy access to the Runway Resource from the `page` variable on a runway route. I've opted to leave the `model` property as protected (as there's probably a reason for that choice).
I've also refactored the `template` and `layout` methods to utilise the new `resource` method, for consistency. Tests for these methods are passing.
Also adds a test for the new `resource` method.
For more context, please see Discord thread: https://discord.com/channels/489818810157891584/1151898550305837086/1403406370275065918
^ If the Discord link above is inaccessible, I'm building a admin toolbar (like WordPress) that's visible on the frontend, and allows the user to edit the entry they're currently on, amongst other things. I'd got …
=> [8.x] Update RoutingModel model property to be publicly accessible

src/Traits/HasRunwayResource.php
We've implemented functionality in our https://github.com/rapidez/statamic package that adds a hidden collection to a Runway resource, including the collection's fields in the resource's blueprint.
However, we encountered an issue when adding new fields to the blueprint with names that don't correspond to existing columns in the resource's database table. This correctly throws an error since the column doesn't exist.
This PR adds validation to ensure that all fields being searched against the resource table have corresponding columns in the database.
=> [8.x] Add column existence validation for Runway resource fields

src/Console/Commands/ImportCollection.php
`spl_autoload` function maps classes to lowercase filenames:
https://www.php.net/manual/en/function.spl-autoload.php
https://stackoverflow.com/a/14361521/4171578
When you run `runway:import-collection` on Mac, it works fine, since Mac filesystem is case-insensitive. On Ubuntu, running this throws an exception like:
```
class_parents(): Class App\Models\Post does not exist and could not be loaded
```
I'm running Laravel Sail in WSL2 on Windows. Changing `spl_autoload` to `require_once` fixes the issue.
=> Fix runway:import-collection to run on Ubuntu, and not just Mac

src/Traits/HasRunwayResource.php
This pull request fixes an issue when sorting by a nested field, when the nested field prefix contained multiple underscores, like `frontend_extra_attributes`.
This was happening due to the `HasRunwayResource:: getColumnForField()` method incorrectly identifying the nested field prefix (the name of the JSON column).
Fixes #716
=> Fix sorting by nested fields
